#################################################################################################
# START: custom mod_player_bot_level_brackets.conf settings
#################################################################################################

#-------------------------------------------------------------------
#---- general
#-------------------------------------------------------------------
BotLevelBrackets.Enabled = 1

#-------------------------------------------------------------------
#---- logs
#-------------------------------------------------------------------
BotLevelBrackets.FullDebugMode = 0
BotLevelBrackets.LiteDebugMode = 0

#################################################################################################
# END: custom mod_player_bot_level_brackets.conf settings
#################################################################################################
