#################################################################################################
# START: custom mod_player_bot_level_brackets.conf settings
#################################################################################################

#-------------------------------------------------------------------
#---- general
#-------------------------------------------------------------------
BotLevelBrackets.Enabled = 1
BotLevelBrackets.Dynamic.UseDynamicDistribution = 0

#-------------------------------------------------------------------
#---- logs
#-------------------------------------------------------------------
BotLevelBrackets.FullDebugMode = 0
BotLevelBrackets.LiteDebugMode = 0

#-------------------------------------------------------------------
#---- frequencies
#-------------------------------------------------------------------
BotLevelBrackets.CheckFrequency = 300
BotLevelBrackets.CheckFlaggedFrequency = 15
BotLevelBrackets.FlaggedProcessLimit = 20

#-------------------------------------------------------------------
#---- brackets (10% for each)
#-------------------------------------------------------------------
BotLevelBrackets.NumRanges = 10
# Alliance
BotLevelBrackets.Alliance.Range1.Lower = 1
BotLevelBrackets.Alliance.Range1.Upper = 9
BotLevelBrackets.Alliance.Range1.Pct   = 10

BotLevelBrackets.Alliance.Range2.Lower = 10
BotLevelBrackets.Alliance.Range2.Upper = 19
BotLevelBrackets.Alliance.Range2.Pct   = 10

BotLevelBrackets.Alliance.Range3.Lower = 20
BotLevelBrackets.Alliance.Range3.Upper = 29
BotLevelBrackets.Alliance.Range3.Pct   = 10

BotLevelBrackets.Alliance.Range4.Lower = 30
BotLevelBrackets.Alliance.Range4.Upper = 39
BotLevelBrackets.Alliance.Range4.Pct   = 10

BotLevelBrackets.Alliance.Range5.Lower = 40
BotLevelBrackets.Alliance.Range5.Upper = 49
BotLevelBrackets.Alliance.Range5.Pct   = 10

BotLevelBrackets.Alliance.Range6.Lower = 50
BotLevelBrackets.Alliance.Range6.Upper = 59
BotLevelBrackets.Alliance.Range6.Pct   = 10

BotLevelBrackets.Alliance.Range7.Lower = 60
BotLevelBrackets.Alliance.Range7.Upper = 69
BotLevelBrackets.Alliance.Range7.Pct   = 10

BotLevelBrackets.Alliance.Range8.Lower = 70
BotLevelBrackets.Alliance.Range8.Upper = 74
BotLevelBrackets.Alliance.Range8.Pct   = 10

BotLevelBrackets.Alliance.Range9.Lower = 75
BotLevelBrackets.Alliance.Range9.Upper = 79
BotLevelBrackets.Alliance.Range9.Pct   = 10

BotLevelBrackets.Alliance.Range10.Lower = 80
BotLevelBrackets.Alliance.Range10.Upper = 80
BotLevelBrackets.Alliance.Range10.Pct   = 10

#################################################################################################
# END: custom mod_player_bot_level_brackets.conf settings
#################################################################################################
