#!/bin/bash

echo "###########################################################################################"
echo "### menu    -  Shows menu"
echo "### install -  Download the source source-code"
echo "### update  -  Updates source-code to latest version"
echo "### build   -  Builds the server based on source-code"
echo "### compile -  Compiles the code based on the build server"
echo "### config  -  Applies the server configration"
echo "### start   -  starts auth and world in tmux sessions server"
echo "### debug   -  starts auth and world debug mode (GDB, timestamped crash logs)"
echo "### stop    -  stops all sessions"
echo "### wow     -  logon world-server (tmux) session"
echo "### auth    -  logon auth-server (tmux) session"
echo "###########################################################################################"
